### ISSUE TITLE
[REQUEST] Update needed

### ISSUE THREAD

**Issue by DevTimur** [Ocelot5836/Just-Enough-Vehicles#1]
vehicle-mod-0.43.0-1.12.2
Game crash with this crashlog

_java.lang.NoSuchFieldError: DISPLAY_PROPERTIES
	at com.ocelot.vehicle.jei.plugin.workstation.VehicleRecipeWrapper.drawInfo(VehicleRecipeWrapper.java:81)
	at mezz.jei.gui.recipes.RecipeLayout.drawRecipe(RecipeLayout.java:158)
	at mezz.jei.gui.recipes.RecipesGui.func_73863_a(RecipesGui.java:222)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)_

**Comment by Ocelot5836** [comment]
Fixed in v1.1
